import { useEffect, useState } from "react";
import { Check, Edit3, ImagePlus, Trash2 } from "lucide-react";
import { StudioShell } from "../components/layout/StudioShell";
import { getStudioVideos, updateStudioThumbnail, updateStudioVideo, toggleStudioPublish, deleteStudioVideo } from "../api/studio";
import type { StudioVideo } from "../types/studio";
import { getApiErrorMessage } from "../utils/apiError";
import { Skeleton } from "../components/ui/Skeleton";
import { ErrorState } from "../components/ui/ErrorState";
import { EmptyState } from "../components/ui/EmptyState";
import { Button } from "../components/ui/Button";
import { Input } from "../components/ui/Input";
import { Textarea } from "../components/ui/Textarea";
import { Modal } from "../components/ui/Modal";
import { ConfirmDialog } from "../components/ui/ConfirmDialog";

export default function StudioVideosPage() {
  const [videos, setVideos] = useState<StudioVideo[]>([]); const [statuses, setStatuses] = useState<Record<string, boolean>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState<StudioVideo | null>(null); const [deleting, setDeleting] = useState<StudioVideo | null>(null); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const loadedVideos = await getStudioVideos(); setVideos(loadedVideos); setStatuses(Object.fromEntries(loadedVideos.map((video) => [video._id, Boolean(video.isPublished)]))); } catch (requestError) { setError(getApiErrorMessage(requestError, "Your videos could not be loaded.")); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  const saveEdit = async (title: string, description: string) => { if (!editing) return; setSaving(true); try { const updated = await updateStudioVideo(editing._id, title, description); setVideos((current) => current.map((video) => video._id === updated._id ? { ...video, ...updated } : video)); setEditing(null); setNotice("Video details updated."); } catch (requestError) { setError(getApiErrorMessage(requestError, "Video details could not be updated.")); } finally { setSaving(false); } };
  const updateThumbnail = async (videoId: string, file?: File) => { if (!file) return; setSaving(true); try { const updated = await updateStudioThumbnail(videoId, file); setVideos((current) => current.map((video) => video._id === updated._id ? { ...video, ...updated } : video)); setNotice("Thumbnail updated."); } catch (requestError) { setError(getApiErrorMessage(requestError, "Thumbnail could not be updated.")); } finally { setSaving(false); } };
  const publish = async (video: StudioVideo) => { setSaving(true); try { const updated = await toggleStudioPublish(video._id, !(statuses[video._id] ?? video.isPublished ?? false)); setStatuses((current) => ({ ...current, [video._id]: Boolean(updated.isPublished) })); setNotice("Publish status updated."); } catch (requestError) { setError(getApiErrorMessage(requestError, "Publish status could not be updated.")); } finally { setSaving(false); } };
  const remove = async () => { if (!deleting) return; setSaving(true); try { await deleteStudioVideo(deleting._id); setVideos((current) => current.filter((video) => video._id !== deleting._id)); setDeleting(null); setNotice("Video deleted."); } catch (requestError) { setError(getApiErrorMessage(requestError, "Video could not be deleted.")); } finally { setSaving(false); } };
  return <StudioShell><div className="max-w-6xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-amber-300">Content library</p><h2 className="mt-2 text-3xl font-semibold tracking-tight text-slate-100">Manage your videos.</h2></div>{notice && <p role="status" className="flex items-center gap-2 text-sm text-emerald-300"><Check size={16} />{notice}</p>}</div>{loading ? <div className="space-y-3">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="h-28 rounded-2xl" />)}</div> : error && !videos.length ? <ErrorState description={error} action={<Button onClick={() => void load()}>Try again</Button>} /> : !videos.length ? <EmptyState title="No creator videos yet" description="Upload your first video to start building the library." /> : <div className="space-y-3">{videos.map((video) => <article key={video._id} className="flex flex-col gap-4 rounded-2xl border border-slate-800 bg-slate-950/50 p-4 sm:flex-row sm:items-center"><div className="aspect-video w-full shrink-0 overflow-hidden rounded-xl bg-slate-900 sm:w-44">{video.thumbnail?.url && <img src={video.thumbnail.url} alt="" className="size-full object-cover" />}</div><div className="min-w-0 flex-1"><h3 className="truncate font-semibold text-slate-100">{video.title}</h3><p className="mt-1 text-sm text-slate-500">{new Intl.NumberFormat("en", { notation: "compact" }).format(video.views || 0)} views · {video.createdAt ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(video.createdAt)) : "Date unavailable"}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="ghost" onClick={() => setEditing(video)}><Edit3 size={14} />Edit</Button><label className="inline-flex h-8 cursor-pointer items-center gap-2 rounded-xl px-3 text-xs font-medium text-slate-400 hover:bg-slate-800 hover:text-slate-100"><ImagePlus size={14} />Thumbnail<input type="file" accept="image/*" className="sr-only" onChange={(event) => void updateThumbnail(video._id, event.target.files?.[0])} /></label><Button size="sm" variant="ghost" onClick={() => void publish(video)} disabled={saving}>{statuses[video._id] ? "Unpublish" : "Publish"}</Button><Button size="sm" variant="ghost" onClick={() => setDeleting(video)}><Trash2 size={14} />Delete</Button></div></div></article>)}</div>}{error && videos.length > 0 && <p role="alert" className="mt-4 text-sm text-rose-300">{error}</p>}</div><EditVideoModal key={editing?._id || "closed"} video={editing} loading={saving} onClose={() => setEditing(null)} onSave={saveEdit} /><ConfirmDialog open={Boolean(deleting)} title="Delete this video?" description="This permanently deletes the selected video and its media from the creator library." confirmLabel="Delete video" onClose={() => setDeleting(null)} onConfirm={() => void remove()} /></StudioShell>;
}

function EditVideoModal({ video, loading, onClose, onSave }: { video: StudioVideo | null; loading: boolean; onClose: () => void; onSave: (title: string, description: string) => Promise<void> }) {
  const [title, setTitle] = useState(video?.title || ""); const [description, setDescription] = useState(video?.description || "");
  return <Modal open={Boolean(video)} title="Edit video details" onClose={onClose}><div className="space-y-4"><Input id="edit-title" label="Title" value={title} onChange={(event) => setTitle(event.target.value)} /><Textarea id="edit-description" label="Description" value={description} onChange={(event) => setDescription(event.target.value)} /><div className="flex justify-end gap-2"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button variant="primary" disabled={loading || !title.trim()} onClick={() => void onSave(title.trim(), description)}>Save changes</Button></div></div></Modal>;
}
