import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { CheckCircle2, FileVideo, ImagePlus, UploadCloud } from "lucide-react";
import { StudioShell } from "../components/layout/StudioShell";
import { Button } from "../components/ui/Button";
import { Input } from "../components/ui/Input";
import { Textarea } from "../components/ui/Textarea";
import { uploadVideo } from "../api/studio";
import { getApiErrorMessage } from "../utils/apiError";

export default function StudioUploadPage() {
  const [video, setVideo] = useState<File | null>(null); const [thumbnail, setThumbnail] = useState<File | null>(null); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [dragging, setDragging] = useState(false); const [progress, setProgress] = useState(0); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const [preview, setPreview] = useState("");
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  const chooseVideo = (file?: File) => { if (file?.type.startsWith("video/")) { setVideo(file); setPreview(URL.createObjectURL(file)); } else if (file) setError("Choose a video file."); };
  const chooseThumbnail = (file?: File) => { if (file?.type.startsWith("image/")) setThumbnail(file); else if (file) setError("Choose an image thumbnail."); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!video || !thumbnail || !title.trim()) { setError("Video, thumbnail, and title are required."); return; } setError(""); setSuccess(""); setProgress(0); setLoading(true); try { const result = await uploadVideo({ video, thumbnail, title: title.trim(), description }, setProgress); setSuccess(result.message || "Video uploaded successfully."); setVideo(null); setThumbnail(null); setPreview(""); setTitle(""); setDescription(""); } catch (requestError) { setError(getApiErrorMessage(requestError, "Upload failed.")); } finally { setLoading(false); } };
  return <StudioShell><div className="max-w-4xl"><div className="mb-8"><p className="text-sm text-amber-300">Publish a new video</p><h2 className="mt-2 text-3xl font-semibold tracking-tight text-slate-100">Share something with your audience.</h2><p className="mt-3 text-sm text-slate-500">Upload your media, add context, and publish when it is ready.</p></div><form onSubmit={submit} className="grid gap-5 lg:grid-cols-[1fr_280px]"><div className="space-y-5"><DropZone label="Video file" icon={<FileVideo size={24} />} file={video} dragging={dragging} onDragEnter={() => setDragging(true)} onDragLeave={() => setDragging(false)} onDrop={(file) => { setDragging(false); chooseVideo(file); }} onChange={chooseVideo} accept="video/*" /><Input id="title" label="Title" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Give your video a clear title" required /><Textarea id="description" label="Description" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Tell viewers what this video is about" /><div className="flex items-center justify-between gap-4">{error && <p role="alert" className="text-sm text-rose-300">{error}</p>}{success && <p role="status" className="flex items-center gap-2 text-sm text-emerald-300"><CheckCircle2 size={16} />{success} <Link to="/studio/videos" className="font-medium text-amber-200 hover:text-amber-100">Manage videos</Link></p>}<Button type="submit" variant="primary" className="ml-auto" disabled={loading}>{loading ? `Uploading ${progress}%` : "Upload video"}</Button></div>{loading && <div className="h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-amber-300 transition-[width] duration-200" style={{ width: `${progress}%` }} /></div>}</div><div className="space-y-4"><DropZone label="Thumbnail" icon={<ImagePlus size={24} />} file={thumbnail} onDrop={chooseThumbnail} onChange={chooseThumbnail} accept="image/*" /><div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-950">{preview ? <video src={preview} controls className="aspect-video w-full object-contain" /> : <div className="flex aspect-video items-center justify-center text-center text-xs text-slate-600">Video preview appears here</div>}</div></div></form></div></StudioShell>;
}

function DropZone({ label, icon, file, dragging, onDragEnter, onDragLeave, onDrop, onChange, accept }: { label: string; icon: React.ReactNode; file: File | null; dragging?: boolean; onDragEnter?: () => void; onDragLeave?: () => void; onDrop: (file?: File) => void; onChange: (file?: File) => void; accept: string }) {
  return <label className={`block cursor-pointer rounded-2xl border border-dashed p-5 transition-colors ${dragging ? "border-amber-300 bg-amber-300/10" : "border-slate-700 bg-slate-950/30 hover:border-slate-500"}`} onDragOver={(event) => { event.preventDefault(); onDragEnter?.(); }} onDragLeave={onDragLeave} onDrop={(event) => { event.preventDefault(); onDrop(event.dataTransfer.files[0]); }}><input type="file" accept={accept} className="sr-only" onChange={(event) => onChange(event.target.files?.[0])} /><div className="flex items-center gap-3 text-slate-400">{icon}<div><p className="text-sm font-medium text-slate-200">{label}</p><p className="mt-1 max-w-56 truncate text-xs text-slate-600">{file ? file.name : "Drop a file here or browse"}</p></div></div><UploadCloud className="mt-5 text-slate-600" size={20} /></label>;
}
